namespace PhoenixmlDb.Conformance.Tests.Xslt;

/// <summary>
/// Every element and attribute of the W3C XSLT 3.0 test catalog vocabulary, sorted into what
/// <see cref="XsltTestRunner"/> implements, what it deliberately ignores, and what it does not
/// implement yet. <see cref="HarnessVocabularyTests"/> fails on anything in none of them.
/// </summary>
/// <remarks>
/// The QT3 harness in phoenixmldb-xquery lost over 400 cases to catalog features it never
/// read, each silently scoring correct output as wrong (#115-#124 there). This harness was
/// audited the same way on 2026-09-30 and is in better shape: its largest gap overlaps 17
/// failing cases. The guard keeps it that way; an entry leaves KnownGaps when implemented.
/// Attribute keys are "element@attribute".
/// </remarks>
public static class HarnessVocabulary
{
    /// <summary>Implemented by the runner.</summary>
    public static readonly IReadOnlySet<string> Handled = new HashSet<string>(StringComparer.Ordinal)
    {
        "all-of",
        "any-of",
        "assert",
        "assert-count",
        "assert-deep-eq",
        "assert-empty",
        "assert-eq",
        "assert-message",
        "assert-result-document",
        "assert-result-document@uri",
        "assert-serialization",
        "assert-serialization-error",
        "assert-serialization-error@code",
        "assert-serialization@encoding",
        "assert-serialization@file",
        "assert-string-value",
        "assert-type",
        "assert-warning",
        "assert-xml",
        "assert-xml@file",
        "assert-xml@ignore-prefixes",
        "assert-xml@xml-version",
        "collection",
        "collection@uri",
        "content",
        "dependencies",
        "description",
        "enable_assertions",
        "enable_assertions@satisfied",
        "environment",
        "environment@name",
        "environment@ref",
        "error",
        "error@code",
        "feature",
        "feature@satisfied",
        "feature@value",
        "ignore_doc_failure",
        "ignore_doc_failure@satisfied",
        "initial-function",
        "initial-function@name",
        "initial-mode",
        "initial-mode@name",
        "initial-mode@select",
        "initial-template",
        "initial-template@name",
        "maximum_number_of_decimal_digits",
        "maximum_number_of_decimal_digits@value",
        "not",
        "on-multiple-match",
        "on-multiple-match@value",
        "output",
        "output@file",
        "package",
        "package@file",
        "package@name",
        "package@package-version",
        "package@role",
        "package@uri",
        "package_version_resolution",
        "package_version_resolution@satisfied",
        "package_version_resolution@value",
        "param",
        "param@as",
        "param@name",
        "param@select",
        "param@static",
        "param@tunnel",
        "result",
        "serialization-matches",
        "serialization-matches@flags",
        "source",
        "source@file",
        "source@role",
        "source@select",
        "source@streaming",
        "source@uri",
        "source@xinclude",
        "source@xml-version",
        "spec",
        "spec@value",
        "stylesheet",
        "stylesheet@file",
        "stylesheet@role",
        "stylesheet@xml-version",
        "test",
        "test-case",
        "test-case@name",
        "test-set",
        "test-set@file",
        "test-set@name",
        "year_component_values",
        "year_component_values@satisfied",
        "year_component_values@value",
    };

    /// <summary>Deliberately not read: metadata that changes no result.</summary>
    public static readonly IReadOnlyDictionary<string, string> Ignored = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["catalog"] = "suite root",
        ["created"] = "provenance",
        ["created@by"] = "provenance",
        ["created@on"] = "provenance",
        ["keywords"] = "topic metadata",
        ["link"] = "spec cross-reference",
        ["link@section-number"] = "spec cross-reference",
        ["modified"] = "provenance",
        ["modified@by"] = "provenance",
        ["modified@change"] = "provenance",
        ["modified@on"] = "provenance",
        ["result@early-exit-possible"] = "optimisation hint; no result changes",
        ["test-set@{http://www.w3.org/2001/XMLSchema-instance}schemaLocation"] = "schema hint for the catalog file itself",
    };

    /// <summary>Catalog features the runner does not implement yet (failing counts as of 2026-09-30).</summary>
    public static readonly IReadOnlyDictionary<string, string> KnownGaps = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["additional_normalization_form"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["additional_normalization_form@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["assert-serialization@method"] = "the serialization method to assert under is not read",
        ["available_documents"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["available_documents@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["collation"] = "environment collations are not declared (1 failing)",
        ["collation@uri"] = "environment collations are not declared",
        ["combinations_for_numbering"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["combinations_for_numbering@range"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["combinations_for_numbering@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_calendar_in_date_formatting_functions"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_calendar_in_date_formatting_functions@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_html_version"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_html_version@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_language_for_numbering"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_language_for_numbering@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_output_encoding"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["default_output_encoding@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["detect_accumulator_cycles"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["extension-function"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["extension-function@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["languages_for_numbering"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["languages_for_numbering@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["ordinal_scheme_name"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["ordinal_scheme_name@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["output@result-var"] = "binding the result to a variable is not read",
        ["output@serialize"] = "serialize=\"yes\" (compare the serialized result) is not read; 17 failing cases on 2026-09-30, mostly serialization engine work",
        ["output@tree"] = "tree=\"no\" is not read (3 failing)",
        ["output@well-formed"] = "well-formed=\"no\" is not read (3 failing)",
        ["recognize_id_as_uri_fragment"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["resource"] = "environment resources are not registered (3 failing: load-xquery-module)",
        ["resource@encoding"] = "environment resources are not registered",
        ["resource@file"] = "environment resources are not registered",
        ["resource@media-type"] = "environment resources are not registered",
        ["resource@uri"] = "environment resources are not registered",
        ["schema"] = "environment schemas are not read (schema-aware cases; 8 failing)",
        ["schema@file"] = "environment schemas are not read",
        ["schema@role"] = "environment schemas are not read",
        ["schema@uri"] = "environment schemas are not read",
        ["schema@xsd-version"] = "environment schemas are not read",
        ["source@defines-stylesheet"] = "a source that is also the stylesheet is not recognised",
        ["source@validation"] = "source validation is not applied (1 failing)",
        ["supported_calendars_in_date_formatting_functions"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["supported_calendars_in_date_formatting_functions@satisfied"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["supported_calendars_in_date_formatting_functions@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["unicode-version"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["unicode-version@satisfied"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["unicode-version@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["unparsed_text_encoding"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
        ["unparsed_text_encoding@value"] = "implementation-defined dependency not evaluated; cases requiring it run regardless",
    };
}
